name: Docker镜像同步(新增)
permissions: write-all
on:
  workflow_dispatch:
    inputs:
      dockerhub_image:
        description: '输入 DockerHub 镜像名称 (例如: nginx 或 organization/image)'
        required: true
        type: string
      tag:
        description: '输入镜像标签 (例如: latest)'
        required: true
        type: string
      ghcr_image:
        description: '推送到GHCR.IO的镜像名称'
        required: true
        default: 'myimage'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ inputs.ghcr_image }}
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create update workflow
        run: |
          mkdir -p .github/workflows
          # 设置环境变量
          DOCKERHUB_IMAGE="${{ inputs.dockerhub_image }}"
          TAG="${{ inputs.tag }}"
          GHCR_IMAGE="${{ inputs.ghcr_image }}"
          # 将镜像名称中的 / 替换为 - 
          SAFE_NAME=$(echo "$DOCKERHUB_IMAGE" | tr '/' '-')
          
          cat > ".github/workflows/${SAFE_NAME}-update.yml" << 'EOL'
          name: Update Docker Image
          permissions: write-all
          on:
            workflow_dispatch:
          env:
            DOCKERHUB_IMAGE: ${DOCKERHUB_IMAGE}
            TAG: ${TAG}
            GHCR_IMAGE: ${GHCR_IMAGE}
          jobs:
            update:
              runs-on: ubuntu-latest
              steps:
                - uses: docker/login-action@v3
                  with:
                    registry: ghcr.io
                    username: ${GITHUB_ACTOR}
                    password: ${GITHUB_TOKEN}
                - run: docker pull ${DOCKERHUB_IMAGE}:${TAG}
                - run: docker tag ${DOCKERHUB_IMAGE}:${TAG} ghcr.io/${GITHUB_ACTOR}/${GHCR_IMAGE}:${TAG}
                - run: docker push ghcr.io/${GITHUB_ACTOR}/${GHCR_IMAGE}:${TAG}
          EOL
          
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .github/workflows/
          git commit -m "Add update workflow for ${DOCKERHUB_IMAGE}:${TAG}"
          git push

      - name: 登录到GitHub容器注册表
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 拉取Docker镜像
        run: docker pull ${{ inputs.dockerhub_image }}:${{ inputs.tag }}
      
      - name: 标记Docker镜像
        run: docker tag ${{ inputs.dockerhub_image }}:${{ inputs.tag }} ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ inputs.tag }}
      
      - name: 推送Docker镜像
        run: docker push ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ inputs.tag }}
