name: Docker镜像同步(更新)
permissions: write-all

on:
  workflow_dispatch:
    inputs:
      dockerhub_image:
        description: '选择要更新的镜像'
        required: true
        type: choice
        options: |
          ${{ steps.get_images.outputs.images }}
      tag:
        description: '选择标签'
        required: true
        type: choice
        options: |
          latest
          v1.52.3
          v1.52.2
          v1.52.0
          v1.51.16
      ghcr_image:
        description: '推送到GHCR.IO的镜像名称'
        required: true
        default: 'myimage'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ inputs.ghcr_image }}

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 获取可用镜像
        id: get_images
        run: |
          IMAGES=$(jq -r '.images | keys[]' docker-images.json)
          echo "images=$IMAGES" >> $GITHUB_OUTPUT

      - name: 获取可用标签
        id: get_tags
        run: |
          TAGS=$(jq -r --arg img "${{ inputs.dockerhub_image }}" '.images[$img][]' docker-images.json)
          echo "tags=$TAGS" >> $GITHUB_OUTPUT

      - name: 登录到GitHub容器注册表
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 从DockerHub拉取Docker镜像
        run: |
          docker pull ${{ inputs.dockerhub_image }}:${{ inputs.tag }}

      - name: 设置小写的 GitHub 用户名
        run: echo "ACTOR_LOWER=$(echo '${{ github.actor }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: 为GitHub容器注册表标记Docker镜像
        run: |
          docker tag ${{ inputs.dockerhub_image }}:${{ inputs.tag }} ${{ env.REGISTRY }}/${{ env.ACTOR_LOWER }}/${{ env.IMAGE_NAME }}:${{ inputs.tag }}

      - name: 将Docker镜像推送到GitHub容器注册表
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.ACTOR_LOWER }}/${{ env.IMAGE_NAME }}:${{ inputs.tag }}
