name: Docker镜像同步(更新)
permissions: write-all

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate matrix
        id: set-matrix
        run: |
          if [ -f docker-images.json ]; then
            echo "matrix=$(cat docker-images.json)" >> $GITHUB_OUTPUT
          else
            echo "matrix={\"images\":{}}" >> $GITHUB_OUTPUT
          fi

  update:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Show available options
        id: get-options
        run: |
          IMAGES=$(echo '${{ needs.setup.outputs.matrix }}' | jq -r '.images | keys[]')
          echo "Available images:"
          echo "$IMAGES"
          
          # 创建一个临时 workflow 文件
          cat > temp-workflow.yml <<EOF
          name: Docker镜像同步(更新)
          on:
            workflow_dispatch:
              inputs:
                dockerhub_image:
                  description: '选择要更新的镜像'
                  required: true
                  type: choice
                  options:
                    ${{ join(fromJson(needs.setup.outputs.matrix).images | keys, '\n    - ') }}
                tag:
                  description: '选择镜像标签'
                  required: true
                  type: choice
                  options:
                    ${{ join(fromJson(needs.setup.outputs.matrix).images[inputs.dockerhub_image], '\n    - ') }}
                ghcr_image:
                  description: '推送到GHCR.IO的镜像名称'
                  required: true
                  default: 'myimage'
          EOF
          
          mv temp-workflow.yml .github/workflows/docker-mirror-update.yml
          
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .github/workflows/docker-mirror-update.yml
          git commit -m "Update workflow with current options"
          git push

      - name: 登录到GitHub容器注册表
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 从DockerHub拉取Docker镜像
        run: |
          docker pull ${{ inputs.dockerhub_image }}:${{ inputs.tag }}

      - name: 设置小写的 GitHub 用户名
        run: echo "ACTOR_LOWER=$(echo '${{ github.actor }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: 为GitHub容器注册表标记Docker镜像
        run: |
          docker tag ${{ inputs.dockerhub_image }}:${{ inputs.tag }} ${{ env.REGISTRY }}/${{ env.ACTOR_LOWER }}/${{ env.IMAGE_NAME }}:${{ inputs.tag }}

      - name: 将Docker镜像推送到GitHub容器注册表
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.ACTOR_LOWER }}/${{ env.IMAGE_NAME }}:${{ inputs.tag }}
