name: Docker镜像同步(新增)
permissions: write-all        

on:
  workflow_dispatch:
    inputs:
      dockerhub_image:
        description: '输入 DockerHub 镜像名称 (例如: nginx 或 organization/image)'
        required: true
        type: string
      tag:
        description: '输入镜像标签 (例如: latest)'
        required: true
        type: string
      ghcr_image:
        description: '推送到GHCR.IO的镜像名称'
        required: true
        default: 'myimage'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ inputs.ghcr_image }}

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create update workflow
        run: |
          mkdir -p .github/workflows
          SAFE_NAME=$(echo "${{ inputs.dockerhub_image }}" | tr '/' '-')
          
          echo "name: Update ${{ inputs.dockerhub_image }}:${{ inputs.tag }}
permissions: write-all
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ inputs.ghcr_image }}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          registry: \${{ env.REGISTRY }}
          username: \${{ github.actor }}
          password: \${{ secrets.GITHUB_TOKEN }}
          
      - name: 拉取Docker镜像
        run: docker pull ${{ inputs.dockerhub_image }}:${{ inputs.tag }}
      
      - name: 设置用户名
        run: echo \"ACTOR_LOWER=\$(echo '\${{ github.actor }}' | tr '[:upper:]' '[:lower:]')\" >> \$GITHUB_ENV
      
      - name: 标记Docker镜像
        run: docker tag ${{ inputs.dockerhub_image }}:${{ inputs.tag }} \${{ env.REGISTRY }}/\${{ env.ACTOR_LOWER }}/\${{ env.IMAGE_NAME }}:${{ inputs.tag }}
      
      - name: 推送Docker镜像
        run: docker push \${{ env.REGISTRY }}/\${{ env.ACTOR_LOWER }}/\${{ env.IMAGE_NAME }}:${{ inputs.tag }}" > ".github/workflows/${SAFE_NAME}-update.yml"
          
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .github/workflows/
          git commit -m "Add update workflow for ${{ inputs.dockerhub_image }}:${{ inputs.tag }}"
          git push

      - name: 登录到GitHub容器注册表
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 拉取Docker镜像
        run: docker pull ${{ inputs.dockerhub_image }}:${{ inputs.tag }}
      
      - name: 标记Docker镜像
        run: docker tag ${{ inputs.dockerhub_image }}:${{ inputs.tag }} ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ inputs.tag }}
      
      - name: 推送Docker镜像
        run: docker push ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ inputs.tag }}
